#!/usr/bin/env python3
"""Generate checked-in browser resources. Run with --check in CI to detect drift."""
import argparse
import json
from pathlib import Path
import re

root = Path(__file__).resolve().parents[1]
source = root / 'src/BeNobat.Web/Resources'
target = root / 'src/BeNobat.Web/wwwroot/i18n'
parser = argparse.ArgumentParser()
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
messages = {}
for number, line in enumerate((source / 'WebTranslations.tsv').read_text().splitlines(), 1):
    if not line.strip():
        continue
    cells = line.split('\t')
    if len(cells) != 3 or any(not cell.strip() for cell in cells):
        raise SystemExit(f'Invalid resource row {number}: expected fa, en, ar.')
    fa, en, ar = cells
    key = re.sub(r'\s+', ' ', fa).strip()
    value = {'fa': key, 'en': en.strip(), 'ar': ar.strip()}
    if key in messages and messages[key] != value:
        raise SystemExit(f'Conflicting duplicate resource at row {number}: {key}')
    messages[key] = value

# Titles have a localized product suffix. Dynamic business/provider names are
# protected by a data argument in the separate title template.
for title in ('اطلاعات حساب', 'امتیازها و نظرات', 'ثبت‌نام', 'جزئیات', 'خدمات', 'داشبورد مدیریت', 'دسترسی‌های سامانه', 'تقویم نوبت‌ها', 'رزرو نوبت', 'زمان‌های خالی', 'شعب و منابع', 'عدم دسترسی', 'علاقه‌مندی‌ها', 'مدیریت دسته‌بندی‌ها', 'مدیریت کل سامانه', 'نظرات مشتریان', 'نوبت‌های من', 'ورود', 'کاتالوگ خدمات', 'مشتریان', 'اعضای تیم'):
    if title in messages:
        messages[title + ' | به‌نوبت'] = {language: messages[title][language] + ' | ' + messages['به‌نوبت'][language] for language in ('fa', 'en', 'ar')}

templates = json.loads((source / 'WebTemplates.json').read_text())
for template in templates:
    placeholders = set(re.findall(r'\{(\d+)\}', template['fa']))
    if placeholders != {str(i) for i in range(len(template['args']))}:
        raise SystemExit(f'Invalid source placeholders: {template["fa"]}')
    for language in ('en', 'ar'):
        if placeholders != set(re.findall(r'\{(\d+)\}', template[language])):
            raise SystemExit(f'Placeholder mismatch for {language}: {template["fa"]}')
    if any(kind not in ('data', 'number', 'ui') for kind in template['args']):
        raise SystemExit(f'Unknown argument type: {template["fa"]}')

catalog = {'messages': messages, 'templates': templates}
outputs = {
    target / 'catalog.js': '// Generated by tools/update-web-localization.py; edit Resources/WebTranslations.tsv and WebTemplates.json.\nwindow.beNobatCatalog = ' + json.dumps(catalog, ensure_ascii=False, separators=(',', ':')) + ';\n'
}
for language in ('fa', 'en', 'ar'):
    outputs[target / f'{language}.json'] = json.dumps({key: value[language] for key, value in messages.items()}, ensure_ascii=False, indent=2) + '\n'
for path, contents in outputs.items():
    if args.check:
        if not path.exists() or path.read_text() != contents:
            raise SystemExit(f'Resource output is stale: {path.relative_to(root)}')
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(contents)
print(f'{len(messages)} complete messages; {len(templates)} templates; fa/en/ar resources {"verified" if args.check else "generated"}.')
